# Generated by Django 3.1.4 on 2021-01-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=40, verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='-', max_length=8, verbose_name='شماره دانشجویی'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='grade',
            field=models.FloatField(verbose_name='نمره درس'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student', verbose_name='نام دانشجو'),
        ),
    ]
