# Generated by Django 3.1.4 on 2021-01-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20210102_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, default='-', max_length=8, verbose_name='شماره دانشجویی'),
        ),
    ]
