# Generated by Django 3.1.4 on 2021-01-07 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20210102_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='دانشکده')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='نام')),
                ('last_name', models.CharField(max_length=40, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=80, verbose_name='ایمیل')),
                ('website', models.URLField(max_length=80, verbose_name='وب سایت')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='day_of_week',
            field=models.CharField(choices=[('Saturday', 'شنبه'), ('Sunday', 'یک شنبه'), ('Monday', 'دو شنبه'), ('Tuesday', 'سه شنبه'), ('Wednesday', 'چهار شنبه'), ('Thursday', 'پنج شنبه'), ('Friday', 'جمعه')], default='Saturday', max_length=10, verbose_name='روز هفته'),
        ),
        migrations.AddField(
            model_name='course',
            name='from_time',
            field=models.TimeField(null=True, verbose_name='از ساعت'),
        ),
        migrations.AddField(
            model_name='course',
            name='to_time',
            field=models.TimeField(null=True, verbose_name='تا ساعت'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(through='lms.StudentCourse', to='lms.Course'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='اتاق')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.faculty', verbose_name='دانشکده')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.faculty', verbose_name='دانشکده'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.professor', verbose_name='استاد'),
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.room', verbose_name='اتاق'),
        ),
    ]
