# Generated by Django 3.1.4 on 2021-01-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20210107_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'درس', 'verbose_name_plural': 'دروس'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'دانشکده', 'verbose_name_plural': 'دانشکده\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'استاد', 'verbose_name_plural': 'اساتید'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'اتاق', 'verbose_name_plural': 'اتاق\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'دانشجو', 'verbose_name_plural': 'دانشجویان'},
        ),
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'verbose_name': 'دانشجو-درس', 'verbose_name_plural': 'دانشجویان-دروس'},
        ),
        migrations.AddField(
            model_name='student',
            name='graduated',
            field=models.BooleanField(default=False, verbose_name='فارغ التحصیل'),
        ),
    ]
